spring.application.name=portfolio-backend
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dontresor922@gmail.com
spring.mail.password=wppv ckwv zins iqrm

# Additional Email Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional: Logging
logging.level.org.springframework.mail=DEBUG